// Generated by CoffeeScript 1.7.1
$(function() {

  /*
   *リストのタイトルをクリックしたら、
   *リストの詳細が表示されるjavascript
   */
  $('ul.jsSample li').click(function() {
    var _text;
    _text = $(this).find('span.content').text();
    $('div.contentViewer').text(_text);
    return false;
  });
  return false;
});
