// Generated by CoffeeScript 1.7.1
var Hoge, h1, h2;

Hoge = (function() {
  function Hoge() {
    this.someInstanceProp = [1, 2, 3];
  }

  Hoge.prototype.someInstanceMethod = function() {
    this.callAnotherInstanceMethod();
    return alert(this.someInstanceProp);
  };

  Hoge.someClassProp = "hogehoge";

  Hoge.someClassMethod = function() {
    this.callAnotherClassMethod();
    return alert(this.someClassProp);
  };

  return Hoge;

})();

h1 = new Hoge();

alert(h1.someInstanceProp);

h1.someInstanceProp.reverse();

alert(h1.someInstanceProp);

h2 = new Hoge();

alert(h2.someInstanceProp);
