// Generated by CoffeeScript 1.7.1
var Hoge;

Hoge = (function() {
  function Hoge(joo) {
    this.joo = joo;
  }

  Hoge.prototype.test = function() {
    return this.joo;
  };

  Hoge.prototype.getX = function() {
    return this.x;
  };

  Hoge.setXXX = function() {
    return x;
  };

  return Hoge;

})();
